# Generated by Django 4.1.7 on 2023-05-01 14:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("app", "0005_comment")]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="image",
            field=models.FileField(
                default="temp.jpg", upload_to="", verbose_name="Путь к картинке"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="date",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="Опубликован",
            ),
        ),
    ]
